# Generated by Django 3.0.14 on 2022-03-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20220330_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag_set',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
