# Generated by Django 3.0.14 on 2022-03-31 08:20

import contents.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_auto_20220330_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to=contents.models.product_images_url, verbose_name='상품 이미지')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.Product')),
            ],
        ),
    ]
