# Generated by Django 3.0.14 on 2022-04-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_auto_20220331_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_like',
        ),
        migrations.RemoveField(
            model_name='product',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
